version: "3.9"

services:
  kvm-vps:
    build: .
    container_name: kvm-vps
    privileged: true
    devices:
      - /dev/kvm:/dev/kvm
    ports:
      - "2222:22"   # SSH ke VM
      - "5900:5900" # VNC access
    deploy:
      resources:
        limits:
          cpus: "8"
          memory: 32G
          
